- hosts: "main_references"
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - gpsd
          - gpsd-clients
          - pps-tools
          - chrony

    - name: Device tree overlay
      ansible.builtin.blockinfile:
        path: /boot/firmware/config.txt
        marker: "# {mark} M0WUT PNT Main Reference Specific"
        block: |
          dtoverlay=pps-gpio,gpiopin=18

      register: dt_updated

    - name: Reboot machines
      ansible.builtin.reboot:
      when:
        dt_updated.changed

    - name: Load kernel modules
      ansible.builtin.blockinfile:
        path: /etc/modules
        marker: "# {mark} M0WUT PNT Main Reference Specific"
        block: |
          pps-gpio
      register: modules_updated

    - name: Reboot machines
      ansible.builtin.reboot:
      when:
        modules_updated.changed

    - name: Setup GPS config
      ansible.builtin.blockinfile:
          path: /etc/default/gpsd
          marker: "# {mark} M0WUT PNT Main Reference Specific"
          block: |
            START_DAEMON="true"
            USBAUTO="true"
            DEVICES="/dev/ttyAMA3 /dev/pps0"
            GPSD_OPTIONS="-n"
      register: gps_config_updated

    - name: Reboot machines
      ansible.builtin.reboot:
      when:
        gps_config_updated.changed

    - name: (Re)Start gpsd service
      ansible.builtin.systemd_service:
        name: gpsd
        state: started
        daemon_reload: true

    - name: Update chrony config
      ansible.builtin.blockinfile:
          path: /etc/chrony/chrony.conf
          marker: "# {mark} M0WUT PNT Main Reference Specific"
          block: |
            refclock SHM 0 refid NMEA offset 0.000 precision 1e-3 poll 3 noselect
            refclock PPS /dev/pps0 refid PPS lock NMEA poll 3 prefer
            allow 0.0.0.0/0
            local stratum 1

    - name: Remove default NTP pools
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        state: absent
        regexp: "^pool "
        
    - name: Remove default NTP servers
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        state: absent
        regexp: "^server "
        

    - name: (Re)Start chrony service
      ansible.builtin.systemd_service:
        name: chrony
        state: started
        daemon_reload: true
      
